### ISSUE TITLE
CI refactoring

### ISSUE THREAD

**Issue by sampullman** [samatechtw/image-api#31]
In our PR commit CI workflow, there is a common setup pattern that can be extracted to a reusable (composite) action.

```yaml
      - name: Set up NodeJS v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install modules
        run: pnpm install
      - name: Build image-rs processor
        run: pnpm run build:image-rs
      - name: Build server
        run: pnpm run build:server
```

Additionally, a few updates can be made:
- PNPM version to latest
- Update to `actions/checkout@v3`
